import { requireCommerceContext } from "@repo/auth/server";
import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import AppSidebar from "@/app/components/app-sidebar";
import Navbar from "@/app/components/Navbar";
import { ThemeProvider } from "@/app/components/providers/ThemeProvider";
import { SidebarProvider } from "@/app/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Cerramos.com",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // This route group is the merchant dashboard. Rendering it requires more than
  // a valid session: the user also needs an attached commerce so the UI can load
  // commerce-scoped stats, products, clients, and payment-link workflows.
  const context = await requireCommerceContext();
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      disableTransitionOnChange
      enableSystem
    >
      <SidebarProvider defaultOpen={defaultOpen}>
        <AppSidebar
          activeCommerce={context.commerce}
          user={{
            email: context.user.email,
            image: context.user.image,
            name: context.user.name,
          }}
        />
        <main className="w-full">
          <Navbar activeCommerce={context.commerce} />
          <div className="px-4">{children}</div>
        </main>
      </SidebarProvider>
    </ThemeProvider>
  );
}
