interface ParaguayStateDefinition {
  cities: string[];
  code: string;
  name: string;
}

interface ParaguayCityRecord {
  id: string;
  name: string;
  stateId: string;
}

interface ParaguayStateRecord {
  cities: ParaguayCityRecord[];
  code: string;
  countryId: string;
  id: string;
  name: string;
}

const slugifyParaguayLocation = (value: string) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();

const paraguayStateDefinitions: ParaguayStateDefinition[] = [
  {
    code: "1",
    name: "Concepción",
    cities: [
      "Arroyito",
      "Azotey",
      "Belén",
      "Concepción",
      "Horqueta",
      "Itacuá",
      "Loreto",
      "Paso Barreto",
      "Paso Horqueta",
      "San Alfredo",
      "San Carlos del Apa",
      "San Lázaro",
      "Sargento José Félix López",
      "Yby Yaú",
    ],
  },
  {
    code: "2",
    name: "San Pedro",
    cities: [
      "Antequera",
      "Capiibary",
      "Choré",
      "General Elizardo Aquino",
      "General Isidoro Resquín",
      "Guayaibí",
      "Itacurubí del Rosario",
      "Liberación",
      "Lima",
      "Nueva Germania",
      "San José del Rosario",
      "San Estanislao",
      "San Pablo",
      "San Pedro de Ycuamandiyú",
      "San Vicente Pancholo",
      "Santa Rosa del Aguaray",
      "Tacuatí",
      "Unión",
      "Veinticinco de Diciembre",
      "Villa del Rosario",
      "Yataity del Norte",
      "Yrybucuá",
    ],
  },
  {
    code: "3",
    name: "Cordillera",
    cities: [
      "Altos",
      "Arroyos y Esteros",
      "Atyrá",
      "Caacupé",
      "Caraguatay",
      "Emboscada",
      "Eusebio Ayala",
      "Isla Pucú",
      "Itacurubí de la Cordillera",
      "Juan de Mena",
      "Loma Grande",
      "Mbocayaty del Yhaguy",
      "Nueva Colombia",
      "Piribebuy",
      "Primero de Marzo",
      "San Bernardino",
      "San José Obrero",
      "Santa Elena",
      "Tobatí",
      "Valenzuela",
    ],
  },
  {
    code: "4",
    name: "Guairá",
    cities: [
      "Borja",
      "Capitán Mauricio José Troche",
      "Coronel Martínez",
      "Doctor Botrell",
      "Félix Pérez Cardozo",
      "General Eugenio Alejandrino Garay",
      "Independencia",
      "Itapé",
      "Iturbe",
      "José A. Fassardi",
      "Mbocayaty del Guairá",
      "Natalicio Talavera",
      "Ñumí",
      "Paso Yobái",
      "San Salvador",
      "Tebicuary",
      "Villarrica",
      "Yataity del Guairá",
    ],
  },
  {
    code: "5",
    name: "Caaguazú",
    cities: [
      "Caaguazú",
      "Carayaó",
      "Coronel Oviedo",
      "Doctor Cecilio Báez",
      "Doctor Juan Eulogio Estigarribia",
      "Doctor Juan Manuel Frutos",
      "José Domingo Ocampos",
      "La Pastora",
      "Mariscal Francisco Solano López",
      "Nueva Londres",
      "Nueva Toledo",
      "Raúl Arsenio Oviedo",
      "Regimiento de Infantería Tres Corrales",
      "Repatriación",
      "San Joaquín",
      "San José de los Arroyos",
      "Santa Rosa del Mbutuy",
      "Simón Bolívar",
      "Tembiaporá",
      "Tres de Febrero",
      "Vaquería",
      "Yhú",
    ],
  },
  {
    code: "6",
    name: "Caazapá",
    cities: [
      "Abaí",
      "Buena Vista",
      "Caazapá",
      "Doctor Moisés Santiago Bertoni",
      "Fulgencio Yegros",
      "General Higinio Morínigo",
      "Maciel",
      "San Juan Nepomuceno",
      "Tavaí",
      "Tres de Mayo",
      "Yuty",
    ],
  },
  {
    code: "7",
    name: "Itapúa",
    cities: [
      "Alto Verá",
      "Bella Vista",
      "Cambyretá",
      "Capitán Meza",
      "Capitán Miranda",
      "Carlos Antonio López",
      "Carmen del Paraná",
      "Coronel José Félix Bogado",
      "Edelira",
      "Encarnación",
      "Fram",
      "General Artigas",
      "General Delgado",
      "Hohenau",
      "Itapúa Poty",
      "Jesús de Tavarangüé",
      "José Leandro Oviedo",
      "La Paz",
      "Mayor Julio Dionisio Otaño",
      "Natalio",
      "Nueva Alborada",
      "Obligado",
      "Pirapó",
      "San Cosme y Damián",
      "San Juan del Paraná",
      "San Pedro del Paraná",
      "San Rafael del Paraná",
      "Tomás Romero Pereira",
      "Trinidad",
      "Yatytay",
    ],
  },
  {
    code: "8",
    name: "Misiones",
    cities: [
      "Ayolas",
      "San Ignacio Guazú",
      "San Juan Bautista",
      "San Miguel",
      "San Patricio",
      "Santa María de Fe",
      "Santa Rosa de Lima",
      "Santiago",
      "Villa Florida",
      "Yabebyry",
    ],
  },
  {
    code: "9",
    name: "Paraguarí",
    cities: [
      "Acahay",
      "Caapucú",
      "Carapeguá",
      "Escobar",
      "General Bernardino Caballero",
      "La Colmena",
      "María Antonia",
      "Mbuyapey",
      "Paraguarí",
      "Pirayú",
      "Quiindy",
      "Quyquyhó",
      "San Roque González de Santa Cruz",
      "Sapucai",
      "Tebicuarymí",
      "Yaguarón",
      "Ybycuí",
      "Ybytymí",
    ],
  },
  {
    code: "10",
    name: "Alto Paraná",
    cities: [
      "Ciudad del Este",
      "Doctor Juan León Mallorquín",
      "Doctor Raúl Peña",
      "Domingo Martínez de Irala",
      "Hernandarias",
      "Iruña",
      "Itakyry",
      "Juan Emiliano O'Leary",
      "Los Cedrales",
      "Mbaracayú",
      "Minga Guazú",
      "Minga Porá",
      "Naranjal",
      "Ñacunday",
      "Presidente Franco",
      "San Alberto",
      "San Cristóbal",
      "Santa Fe del Paraná",
      "Santa Rita",
      "Santa Rosa del Monday",
      "Tavapy",
      "Yguazú",
    ],
  },
  {
    code: "11",
    name: "Central",
    cities: [
      "Areguá",
      "Capiatá",
      "Fernando de la Mora",
      "Guarambaré",
      "Itá",
      "Itauguá",
      "Julián Augusto Saldívar",
      "Lambaré",
      "Limpio",
      "Luque",
      "Mariano Roque Alonso",
      "Nueva Italia",
      "Ñemby",
      "San Antonio",
      "San Lorenzo",
      "Villa Elisa",
      "Villeta",
      "Ypacaraí",
      "Ypané",
    ],
  },
  {
    code: "12",
    name: "Ñeembucú",
    cities: [
      "Alberdi",
      "Cerrito",
      "Desmochados",
      "General José Eduvigis Díaz",
      "Guazú Cuá",
      "Humaitá",
      "Isla Umbú",
      "Laureles",
      "Mayor José Martínez",
      "Paso de Patria",
      "Pilar",
      "San Juan Bautista de Ñeembucú",
      "Tacuaras",
      "Villa Franca",
      "Villa Oliva",
      "Villalbín",
    ],
  },
  {
    code: "13",
    name: "Amambay",
    cities: [
      "Bella Vista Norte",
      "Capitán Bado",
      "Cerro Corá",
      "Karapaí",
      "Pedro Juan Caballero",
      "Zanja Pytá",
    ],
  },
  {
    code: "14",
    name: "Canindeyú",
    cities: [
      "Corpus Christi",
      "Curuguaty",
      "General Francisco Caballero Álvarez",
      "Itanará",
      "Katueté",
      "La Paloma del Espíritu Santo",
      "Laurel",
      "Maracaná",
      "Nueva Esperanza",
      "Puerto Adela",
      "Salto del Guairá",
      "Villa Ygatimí",
      "Yasy Cañy",
      "Yby Pytá",
      "Ybyrarobaná",
      "Ypejhú",
    ],
  },
  {
    code: "15",
    name: "Presidente Hayes",
    cities: [
      "Benjamín Aceval",
      "Campo Aceval",
      "General José María Bruguez",
      "José Falcón",
      "Nanawa",
      "Nueva Asunción",
      "Puerto Pinasco",
      "Teniente Esteban Martínez",
      "Teniente Primero Manuel Irala Fernández",
      "Villa Hayes",
    ],
  },
  {
    code: "16",
    name: "Boquerón",
    cities: [
      "Boquerón",
      "Filadelfia",
      "Loma Plata",
      "Mariscal José Félix Estigarribia",
    ],
  },
  {
    code: "17",
    name: "Alto Paraguay",
    cities: [
      "Bahía Negra",
      "Capitán Carmelo Peralta",
      "Fuerte Olimpo",
      "Puerto Casado",
    ],
  },
  {
    code: "ASU",
    name: "Asunción",
    cities: ["Asunción"],
  },
];

const paraguayCountry = {
  id: "country_py",
  isoCode2: "PY",
  isoCode3: "PRY",
  name: "Paraguay",
} as const;

const paraguayStates: ParaguayStateRecord[] = paraguayStateDefinitions.map(
  ({ cities, code, name }) => {
    const stateId = `state_py_${code.toLowerCase()}`;

    return {
      cities: cities.map((cityName) => ({
        id: `city_py_${code.toLowerCase()}_${slugifyParaguayLocation(cityName)}`,
        name: cityName,
        stateId,
      })),
      code,
      countryId: paraguayCountry.id,
      id: stateId,
      name,
    };
  }
);

const paraguayCities = paraguayStates.flatMap((state) => state.cities);

export { paraguayCities, paraguayCountry, paraguayStates };
export type { ParaguayCityRecord, ParaguayStateRecord };
